var d;d||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,k=!!globalThis.WorkerGlobalScope,l=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",n=(a,b)=>{throw b;},p=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?p=__filename:k&&(p=self.location.href);var q="",r,t;
if(l){var fs=require("node:fs");q=__dirname+"/";t=a=>{a=u(a)?new URL(a):a;return fs.readFileSync(a)};r=async a=>{a=u(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);typeof module!="undefined"&&(module.exports=d);n=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||k){try{q=(new URL(".",p)).href}catch{}k&&(t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});r=async a=>{if(u(a))return new Promise((c,f)=>
{var g=new XMLHttpRequest;g.open("GET",a,!0);g.responseType="arraybuffer";g.onload=()=>{g.status==200||g.status==0&&g.response?c(g.response):f(g.status)};g.onerror=f;g.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var v=console.log.bind(console),w=console.error.bind(console),x=!1,y,u=a=>a.startsWith("file://");
function ba(){var a=d.preRun;a&&(typeof a=="function"&&(a=[a]),z.push(...a));for(a=z;a.length>0;)a.shift()(d)}function ca(){var a=d.postRun;a&&(typeof a=="function"&&(a=[a]),A.push(...a));for(a=A;a.length>0;)a.shift()(d)}function B(a){d.onAbort?.(a);a=`Aborted(${a})`;w(a);x=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var C;
async function da(a){try{var b=await r(a);return new Uint8Array(b)}catch{}if(t)a=t(a);else throw"both async and sync fetching of the wasm failed";return a}async function ea(a,b){try{var c=await da(a);return await WebAssembly.instantiate(c,b)}catch(f){w(`failed to asynchronously prepare wasm: ${f}`),B(f)}}
async function fa(a){var b=C;if(!u(b)&&!l)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(f){w(`wasm streaming compile failed: ${f}`),w("falling back to ArrayBuffer instantiation")}return ea(b,a)}class D{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var A=[],z=[],E=!0,F=[],G=0,H={},I=a=>{a instanceof D||a=="unwind"||n(1,a)},J=a=>{y=a;E||G>0||(d.onExit?.(a),x=!0);n(a,new D(a))},ha=a=>{if(!x)try{a()}catch(b){I(b)}finally{if(!(E||G>0))try{y=a=y,J(a)}catch(b){I(b)}}},K=[],L,ia,M,ja,ka,la=(a,b)=>{K.length=0;for(var c;c=L[a++];){var f=c!=105;f&=c!=112;b+=f&&b%8?4:0;K.push(c==112?M[b>>2]:c==106?ka[b>>3]:c==105?ia[b>>2]:ja[b>>3]);b+=f?8:4}return K},ma=[null,[],[]],na=globalThis.TextDecoder&&new TextDecoder,N=(a,b=0)=>{var c=b;for(var f=c+NaN;a[c]&&!(c>=
f);)++c;if(c-b>16&&a.buffer&&na)return na.decode(a.subarray(b,c));for(f="";b<c;){var g=a[b++];if(g&128){var h=a[b++]&63;if((g&224)==192)f+=String.fromCharCode((g&31)<<6|h);else{var e=a[b++]&63;g=(g&240)==224?(g&15)<<12|h<<6|e:(g&7)<<18|h<<12|e<<6|a[b++]&63;g<65536?f+=String.fromCharCode(g):(g-=65536,f+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else f+=String.fromCharCode(g)}return f},O,oa;d.noExitRuntime&&(E=d.noExitRuntime);d.print&&(v=d.print);d.printErr&&(w=d.printErr);var S=d.preInit;
if(S)for(typeof S=="function"&&(d.preInit=S=[S]);S.length>0;)S.shift()();
var wa={27340:(a,b)=>{a=a?N(L,a):"";var c=document.createElement("input");c.id=a;c.type="text";c.maxLength=b;c.style.position="absolute";c.style["font-family"]="Ubuntu";c.style.display="none";c.style["border-width"]="0px";c.style.background="transparent";c.style.border="none";c.style.outline="none";c.style["padding-left"]="2px";document.body.appendChild(c)},27780:a=>{a=a?N(L,a):"";document.getElementById(a).style.display="block"},27889:a=>{a=a?N(L,a):"";a=document.getElementById(a);a.style.display=
"none";a.style.width=a.style.height="0px"},28043:(a,b,c,f,g)=>{a=a?N(L,a):"";a=document.getElementById(a);a.style.left=(b-f/2)/devicePixelRatio+"px";a.style.top=(c-g/2)/devicePixelRatio+"px";a.style.width=f/devicePixelRatio+"px";a.style.height=g/devicePixelRatio+"px";a.style["font-size"]=g/devicePixelRatio*.8+"px"},28400:(a,b,c)=>{a=a?N(L,a):"";a=document.getElementById(a);a=(new TextEncoder).encode(a.value);c=c>a.length?a.length:c;a=a.slice(0,c);L.set(a,b);L[b+c]=0},28642:(a,b)=>{a=a?N(L,a):"";document.getElementById(a).value=
b?N(L,b):""},28752:a=>{a=a?N(L,a):"";document.getElementById(a).focus()},28845:a=>{a=a?N(L,a):"";document.getElementById(a).blur()},28937:a=>{a=a?N(L,a):"";a=document.getElementById(a);return+(document.activeElement===a)},29059:a=>{var b=document.createElement("textarea");b.style.position="fixed";b.style.top=0;b.style.left=0;b.style.width="2em";b.style.height="2em";b.style.margin=0;b.style.padding=0;b.style.border="none";b.style.outline="none";b.style.boxShadow="none";b.style.background="transparent";
b.value=a?N(L,a):"";document.body.appendChild(b);b.focus();b.select();try{document.execCommand("copy")||console.log("execCommand copy failed")}catch(c){}document.body.removeChild(b)},29629:()=>+/iPhone|iPad|iPod|Android/i.test(navigator.userAgent),29700:(a,b)=>{try{b?(window.onbeforeunload=null,window.location.href=a?N(L,a):""):window.open(a?N(L,a):"","_blank").focus()}catch(c){}},29863:a=>{var b="default";switch(a){case 1:b="pointer"}d.canvas.style.cursor=b},29979:a=>{L[a]=0;if(window.rrolfScript){var b=
window.rrolfScript.src.replace("http","ws").replace("8080","1234").replace("rrolf-client.js","");b=(new TextEncoder).encode(b);b.length>=128||(L.set(b,a),L[a+b.length]=0)}},30276:()=>{document.documentElement.requestFullscreen()},30326:()=>{document.exitFullscreen()},30357:()=>+!!document.fullscreenElement,30399:(a,b)=>{a=a?N(L,a):"";b=b?N(L,b):"";window.localStorage[a]=b},30509:(a,b,c)=>{a=a?N(L,a):"";b=(new TextDecoder).decode(L.subarray(b,b+c-1));window.localStorage[a]=b},30657:(a,b)=>{a=a?N(L,
a):"";a=window.localStorage[a];if(!a)return 0;L.set((new TextEncoder).encode(a),b);return a.length},30827:a=>{a=document.getElementById(a?N(L,a):"");a.id!=="_0x4523"&&(a.value=prompt())},30954:a=>{function b(c){var f=Math.min(.5,(c-d.start)/1E3);d.start=c;d.canvas.width=document.documentElement.clientWidth*devicePixelRatio;d.canvas.height=document.documentElement.clientHeight*devicePixelRatio;pa(a,f,d.canvas.width,d.canvas.height,devicePixelRatio);requestAnimationFrame(b)}d.canvas=document.createElement("canvas");
d.canvas.id="canvas";d.canvas.oncontextmenu=function(){return!1};window.onbeforeunload=function(){return"Are you sure?"};document.body.appendChild(d.canvas);d.C=[d.canvas.getContext("2d")];d.D=Array(256).fill(0).map(function(c,f){return f});window.addEventListener("keydown",function(c){T(a,1,c.which,c.key?(!c.ctrlKey&&!c.metaKey&&c.key.length==1)*c.key.charCodeAt():0,+c.repeat,+c.isTrusted)});window.addEventListener("keyup",function(c){T(a,0,c.which,c.key?(!c.ctrlKey&&!c.metaKey&&c.key.length==1)*
c.key.charCodeAt():0,+c.repeat,+c.isTrusted)});window.addEventListener("mousedown",async function(c){U(a,c.clientX*devicePixelRatio,c.clientY*devicePixelRatio,1,+!!c.button,+c.isTrusted)});window.addEventListener("mousemove",async function(c){U(a,c.clientX*devicePixelRatio,c.clientY*devicePixelRatio,2,+!!c.button,+c.isTrusted)});window.addEventListener("mouseup",async function(c){U(a,c.clientX*devicePixelRatio,c.clientY*devicePixelRatio,0,+!!c.button,+c.isTrusted)});window.addEventListener("touchstart",
function(c){c.preventDefault();c.stopPropagation();if(c.changedTouches.length){var f=c.changedTouches[0];U(a,f.clientX*devicePixelRatio,f.clientY*devicePixelRatio,1,0,+c.isTrusted);for(let g of c.changedTouches)V(a,g.clientX*devicePixelRatio,g.clientY*devicePixelRatio,1,g.identifier,+c.isTrusted)}},{passive:!1});window.addEventListener("touchmove",function(c){c.preventDefault();c.stopPropagation();if(c.changedTouches.length){var f=c.changedTouches[0];U(a,f.clientX*devicePixelRatio,f.clientY*devicePixelRatio,
2,0,+c.isTrusted);for(let g of c.changedTouches)V(a,g.clientX*devicePixelRatio,g.clientY*devicePixelRatio,1,g.identifier,+c.isTrusted)}},{passive:!1});window.addEventListener("touchend",function(c){c.preventDefault();c.stopPropagation();if(c.changedTouches.length){var f=c.changedTouches[0];U(a,f.clientX*devicePixelRatio,f.clientY*devicePixelRatio,0,0,+c.isTrusted);for(let g of c.changedTouches)V(a,g.clientX*devicePixelRatio,g.clientY*devicePixelRatio,0,g.identifier,+c.isTrusted)}},{passive:!1});window.addEventListener("wheel",
async function(c){qa(a,c.deltaY,+c.isTrusted)});document.body.addEventListener("paste",async function(c){var f=(new TextEncoder).encode(c.clipboardData.getData("text/plain")),g=W(f.length+1);L.set(f,g);L[g+f.length]=0;ra(a,g,+c.isTrusted)});window.addEventListener("blur",function(c){ta(a,1,+c.isTrusted)});d.F=function(c){if(d.D.length){let f=d.D.shift();if(f==0)return 0;let g=new OffscreenCanvas(1,1);g.addEventListener("contextrestored",function(h){ua(c,1,+h.isTrusted)});d.C[f]=g.getContext("2d");
return f}throw Error("Out of Contexts: Can be fixed by allowing more contexts");};d.G=function(c){if(c==0)throw Error("Tried to delete the main context");d.C[c]=null;d.D.push(c)};d.start=0;requestAnimationFrame(b);setInterval(()=>{if(typeof window.gc==="function")try{window.gc()}catch{}},1E4)},35398:()=>{var a=crypto.randomUUID(),b=new URL("https://discord.com/oauth2/authorize");b.searchParams.set("client_id","1453525695228678349");b.searchParams.set("response_type","code");b.searchParams.set("redirect_uri",
window.location.origin+window.location.pathname);b.searchParams.set("scope","identify guilds.join");b.searchParams.set("state",a);window.localStorage.oauth2_state=a;window.onbeforeunload=null;window.location.href=b},35888:a=>{var b=new URL(window.location),c=b.searchParams.get("uuid")||window.localStorage.rivet_account_uuid||"",f=window.localStorage.DO_NOT_SHARE_account_token||"",g=b.searchParams.get("code")||"",h=b.searchParams.get("state")||"",e=window.localStorage.oauth2_state;g=e&&h&&e===h?g:
"";b.searchParams.delete("uuid");b.searchParams.delete("code");b.searchParams.delete("state");b.searchParams.delete("error");b.searchParams.delete("error_description");window.history.replaceState(null,null,b);delete window.localStorage.oauth2_state;b=W(c.length+1);h=W(f.length+1);e=W(g.length+1);L.set((new TextEncoder).encode(c),b);L.set((new TextEncoder).encode(f),h);L.set((new TextEncoder).encode(g),e);L[b+c.length]=0;L[h+f.length]=0;L[e+g.length]=0;va(b,h,e,a)},37017:(a,b,c)=>{var f=b?N(L,b):"";
d.socket&&d.socket.readyState<2&&d.socket.close();(function(){var g=d.socket=new WebSocket(f);g.binaryType="arraybuffer";g.onopen=function(){X(a,0,0,0)};g.onclose=function(h){X(a,1,0,h.code)};g.onmessage=function(h){L.set(new Uint8Array(h.data),c);X(a,2,c,(new Uint8Array(h.data)).length)}})()},37557:()=>{d.socket&&(d.socket.onopen=null,d.socket.onclose=null,d.socket.onmessage=null,d.socket.readyState<2&&d.socket.close())},37732:(a,b)=>{d.socket.send(L.subarray(a,a+b))},37786:(a,b)=>{d.socket.send(L.subarray(a,
a+b))},37840:a=>d.F(a),37870:(a,b,c)=>{d.C[a].canvas.width=b;d.C[a].canvas.height=c},37945:a=>{a=a?N(L,a):"";d.C[0].font="1px Ubuntu";return d.C[0].measureText(a).width},38065:(a,b,c)=>{for(let g=0;g<b;++g){let h=O[a+2>>1];var f=O[a+4>>1];let e=oa.subarray(a+8>>2,a+32>>2),m=M[a+32>>2];switch(L[a]){case 0:d.C[h].fillStyle="rgba("+e[0]+","+e[1]+","+e[2]+","+e[3]+")";break;case 1:d.C[h].strokeStyle="rgba("+e[0]+","+e[1]+","+e[2]+","+e[3]+")";break;case 2:d.C[h].lineWidth=e[0];break;case 3:d.C[h].font=
e[0]+"px Ubuntu";break;case 4:d.C[h].globalAlpha=e[0];break;case 5:e[0]==0?d.C[h].lineCap="butt":e[0]==1?d.C[h].lineCap="round":e[0]==2&&(d.C[h].lineCap="square");break;case 6:e[0]==0?d.C[h].lineJoin="bevel":e[0]==1?d.C[h].lineJoin="round":e[0]==2&&(d.C[h].lineJoin="miter");break;case 7:e[0]==0?d.C[h].textAlign="left":e[0]==1?d.C[h].textAlign="center":e[0]==2&&(d.C[h].textAlign="right");break;case 8:e[0]==0?d.C[h].textBaseline="top":e[0]==1?d.C[h].textBaseline="middle":e[0]==2&&(d.C[h].textBaseline=
"bottom");break;case 9:d.C[h].setTransform(e[0],e[1],e[3],e[4],e[2],e[5]);break;case 10:d.C[h].save();break;case 11:d.C[h].restore();break;case 12:d.C[h].beginPath();break;case 13:d.C[h].moveTo(e[0],e[1]);break;case 14:d.C[h].lineTo(e[0],e[1]);break;case 15:d.C[h].quadraticCurveTo(e[0],e[1],e[2],e[3]);break;case 16:d.C[h].bezierCurveTo(e[0],e[1],e[2],e[3],e[4],e[5]);break;case 17:d.C[h].arc(e[0],e[1],e[2],e[3],e[4],e[5]);break;case 18:d.C[h].ellipse(e[0],e[1],e[2],e[3],0,6.283185307179586,0);break;
case 19:d.C[h].rect(e[0],e[1],e[2],e[3]);break;case 20:d.C[h].drawImage(d.C[f].canvas,e[0],e[1],e[2],e[3],e[4],e[5],e[2],e[3]);break;case 21:d.C[h].fillRect(e[0],e[1],e[2],e[3]);break;case 22:d.C[h].strokeRect(e[0],e[1],e[2],e[3]);break;case 23:d.C[h].fill();break;case 24:d.C[h].stroke();break;case 25:d.C[h].clip();break;case 26:d.C[h].clip("evenodd");break;case 27:f=m?N(L,m):"";d.C[h].fillText(f,e[0],e[1]);Y(m);break;case 28:f=m?N(L,m):"";d.C[h].strokeText(f,e[0],e[1]);Y(m);break;case 30:e[0]==0?
d.C[h].globalCompositeOperation="source-over":e[0]==1&&(d.C[h].globalCompositeOperation="destination-out")}a+=c}}},W,Y,T,U,V,qa,ra,ua,ta,pa,xa,va,X,ya,za,Aa,Ba={f:(a,b)=>{var c=F[a];c||(F[a]=c=Aa.get(a));return c(b)},i:()=>B(""),h:()=>{E=!1;G=0},d:(a,b)=>{H[a]&&(clearTimeout(H[a].id),delete H[a]);if(!b)return 0;var c=setTimeout(()=>{delete H[a];ha(()=>ya(a,performance.now()))},b);H[a]={id:c,H:b};return 0},j:(a,b,c)=>{b=la(b,c);return wa[a](...b)},a:(a,b,c)=>{b=la(b,c);return wa[a](...b)},c:()=>Date.now(),
e:()=>{B("OOM")},b:(a,b,c,f)=>{for(var g=0,h=0;h<c;h++){var e=M[b>>2],m=M[b+4>>2];b+=8;for(var P=0;P<m;P++){var sa=a,Q=L[e+P],R=ma[sa];Q&&Q!==10?R.push(Q):((sa===1?v:w)(N(R)),R.length=0)}g+=m}M[f>>2]=g;return 0},g:J};function Ca(){var a=xa;try{var b=a(0,0);y=b;J(b)}catch(c){I(c)}}async function Da(){ba();var a=d.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));x||(Z.l(),d.onRuntimeInitialized?.(),d.noInitialRun||Ca(),ca())}var Z;
(async function(){function a(f){f=Z=f.exports;W=d._malloc=f.m;Y=d._free=f.n;d._rr_rivet_lobby_on_find=f.o;T=d._rr_key_event=f.p;U=d._rr_mouse_event=f.q;V=d._rr_touch_event=f.r;qa=d._rr_wheel_event=f.s;ra=d._rr_paste_event=f.t;ua=d._rr_context_event=f.u;ta=d._rr_focus_event=f.v;pa=d._rr_renderer_main_loop=f.w;xa=d._main=f.x;va=d._rr_discord_oauth2_on_log_in=f.y;X=d._rr_on_socket_event_emscripten=f.z;ya=f.B;za=f.k;Aa=f.A;f=za.buffer;L=new Uint8Array(f);O=new Uint16Array(f);ia=new Int32Array(f);M=new Uint32Array(f);
oa=new Float32Array(f);ja=new Float64Array(f);ka=new BigInt64Array(f);return Z}var b={a:Ba},c=d.instantiateWasm;if(c)return new Promise(f=>{c(b,g=>f(a(g)))});C??=d.locateFile?d.locateFile("rrolf-client.wasm",q):q+"rrolf-client.wasm";return function(f){return a(f.instance)}(await fa(b))})().then(()=>Da());
